### ISSUE TITLE
Telegram notifications don't include metrics after v0.8.23

### ISSUE THREAD

**Issue by maxkoshevoi** [sadviq99/db1000n-setup#2]
Most likely `tg_notify.sh` needs to be updated to read new metrics reposted https://github.com/Arriven/db1000n/pull/484

**Comment by sadviq99** [comment]
@maxkoshevoi The issue has been resolved in the PR #3. Please see the update instruction and let me know in case of any issues. 

Slava Ukraine! 🇺🇦
